academics:
- degree: BA, General Studies
  end_date: 05/23/1975
  institution: Queens College
  start_date: 08/08/1971
  website: https://www.qc.cuny.edu/
contact:
  email: george@georgecostanza.com
  location:
    address: 22-37 37th St
    city: Astoria, Queens
    country: United States
    state: NY
    zip: '11105'
  name: George Costanza
  nickname: George
  phone: 1.555.555.5555
cv:
- description: Sitcom pilot-production for NBC.
  production: Jerry
  role: Writer
experiences:
- description: Assisted Traveling Secretary in business, team and stadium initiatives.
  end_date: 05/08/1997
  highlights:
  - Spearheaded initiative replacing polyester player uniforms with cotton uniforms.
  - Built sleeping quarters underneath the desk in my office.
  organization: New York Yankees
  start_date: 05/19/1994
  title: Assistant to the Traveling Secretary
  website: https://www.mlb.com/yankees
interests:
- description: I am a big sports fan, especially baseball!
  name: sports
- description: I watch a ton of TV.
  name: Television
- description: I watch a ton of TV.
  name: Television
introduction:
  job: MLB Assistant
  summary: I have three years of strong experience assisting in all baseball business
    related matters.
  website: https://www.georgecostanza.com/
projects:
- description: Every instinct I have is wrong, so I do the opposite.
  name: Doing the opposite.
  url: https://doingtheopposite.com/
- description: Trying to reclaim all-time high score.
  name: Frogger high score
skills:
- name: Risk-management
  score: 5
- name: Screenwriting
  score: 4
socials:
- platform: LinkedIn
  url: https://www.linkedin.com/in/george-costanza-a89b469/
